apiVersion: mcp.upbound.io/v1alpha1
kind: ControlPlaneAuth
metadata:
  name: controlplane-a-token
spec:
  forProvider:
    controlPlaneNameRef:
      name: controlplane-a
    organizationName: upbound
    tokenSecretRef:
      key: token
      name: up-access-token
      namespace: upbound-system
  writeConnectionSecretToRef:
    name: controlplane-a-kubeconfig
    namespace: upbound-system
